
name: Build, Test and Deploy Shopping List App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project 
      uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install Project Dependencies
      run: npm install
    - name: Run All Unit Tests
      run: npm run test:unit
    - name: Display Username
      run: echo "v_atanasov88"
